### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by static-moonlight** [Guymer/PyGuymer3#8]
Sorry that I am open up an issue like that, but I just don't know any other way to get in contact with you.

I found your [blog post ](https://thomasguymer.co.uk/blog/2018/2018-02-21/) about reading MPLS files, and from there I found this Git repo.

So, all I want is to see the content of a MPLS file and now I am sitting in front of Python code I don't understand. What do I actually need to execute on a command line to read the MPLS? Or do I need to write addition Python code? If yes, is there some example?

**Comment by Guymer** [comment]
Hi,

That's no problem at all. First you need to clone the repository running something like:

```sh
git clone https://github.com/Guymer/PyGuymer3.git
```

You can then either write a Python script or just type your commands interactively in a Python prompt. The functions in this repository return the data from a MPLS file as a Python dictionary to allow you to access and use the data. If all you want to do is just look at the data "by hand" as it were, then you could just save the Python dictionary as a JSON file and look at the file. You might try something like this in a Python prompt (in the folder where you ran the Git clone command earlier):

```python
import json # import the standard Python module "json"
import sys # import the standard Python module "sys"
sys.path.append("PyGuymer3") # allow Python to search for Python modules in the repository that you just downloaded
import pyguymer3 # import my Python module
import pyguymer3.media # import my Python media-specific module
br = "/path/to/Blu-ray" # the path to the Blu-ray
ip = 1 # which playlist (or MPLS file) do you want to read?
info = pyguymer3.media.parse_MPLS_file(br, ip) # load the MPLS file as a Python dictionary
with open("mpls.json", "wt", encoding = "utf-8") as fObj: # create an empty JSON file to write into
    json.dump(info, fObj, ensure_ascii = False, indent = 4, sort_keys = True) # save the Python dictionary as a JSON
```

You should now have a file called "mpls.json" which if you load it up should look something like this:

```json
{
    "AppInfoPlayList": {
        "Length": 14,
        "MiscFlags": 16384,
        "PlaybackType": 1,
        "UOMaskTable": 0
    },
    "PlayList": {
        "Length": 424,
        "NumberOfPlayItems": 1,
        "NumberOfSubPaths": 0,
        "PlayItems": [
            {
                "ClipCodecIdentifier": "M2TS",
                "ClipInformationFileName": "00125",
                "INTime": 524280,
                "IsMultiAngle": false,
                "Length": 416,
                "MiscFlags1": 1,
                "MiscFlags2": 0,
                "OUTTime": 365388780,
                "RefToSTCID": 0,
                "STNTable": {
                    "lots of stuff here ..."
                }
            }
        ]
    }
}
```

Does that help?
